default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_ja_0900_as_cs
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: <%= ENV.fetch("DB_HOST") { '127.0.0.1' } %>

development:
  <<: *default
  database: rails_sandbox_development

test:
  <<: *default
  database: rails_sandbox_test

production:
  <<: *default
  database: rails_sandbox_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
